class ListWords {
  static List<String> verbos = [
    "Correr",
    "Dançar",
    "Comer",
    "Beber",
    "Ler",
    "Escrever",
    "Nadar",
    "Cantar",
    "Dormir",
    "Aplaudir",
    "Cortar",
    "Cozinhar",
    "Pular",
    "Chorar",
    "Sorrir",
    "Brincar",
    "Telefonar",
    "Desenhar",
    "Bater",
    "Ajudar",
    "Abraçar",
    "Beijar",
    "Lavar",
    "Varrer",
    "Pintar",
    "Escovar",
    "Gritar",
    "Sussurrar",
    "Levantar",
    "Sentar",
    "Abrir",
    "Fechar",
    "Consertar",
    "Viajar",
    "Falar",
    "Escutar",
    "Olhar",
    "Esperar",
    "Caminhar",
    "Dirigir",
    "Comprar",
    "Vender",
    "Amarrar",
    "Desamarrar",
    "Construir",
    "Destruir",
    "Colher",
    "Plantar",
    "Pescar",
    "Cavar",
    "Subir",
    "Descer",
    "Procurar",
    "Encontrar",
    "Esconder",
    "Mostrar",
    "Deitar",
    "Tocar",
    "Fumar",
    "Morder",
    "Assoprar",
    "Treinar",
    "Jogar",
    "Lutar",
    "Cavalgar",
    "Navegar",
    "Patinar",
    "Esquiar",
    "Surfar"
  ];
  static List<String> geral = [
    "Natação",
    "Banho",
    "Musculação",
    "Flores",
    "Casa",
    "Igreja",
    "Chá",
    "Sol",
    "Árvore",
    "Música",
    "Pizza",
    "Sorvete",
    "Ônibus",
    "Maçã",
    "Estrela",
    "Basquete",
    "Triste",
    "Espirro",
    "Piada",
    "Chifres",
    "Balé",
    "Elevador",
    "Criança",
    "Bicicleta",
    "Tricô",
    "Crochê",
    "Costura",
    "Acampar",
    "Esquiar",
    "Meditar",
    "Caminhada",
    "Escalada",
    "Rapel",
    "Voo livre",
    "Parapente",
    "Quebra-cabeça"
        "Futebol",
    "Frio",
    "Pirata",
    "Super-herói",
    "Princesa",
    "Samurai",
    "Ninja",
    "Vampiro",
    "Zumbi",
    "Estátua",
    "Pintor",
    "Bebê",
    "Luz",
    "Sombra",
    "Shopping",
    "Pesadelo",
  ];
  static List<String> profissoes = [
    "Bailarina",
    "Doutor",
    "Astronauta",
    "Palhaço",
    "Soldado",
    "Detetive",
    "Chef de cozinha",
    "Policial",
    "Professor",
    "Dentista",
    "Mágico",
    "DJ",
    "Nadador",
    "Ciclista",
    "Surfista",
    "Esquiador",
    "Pescador",
    "Motorista",
    "Jardineiro",
    "Cantor",
    "Baterista",
    "Guitarrista",
    "Pianista",
    "Ator",
    "Diretor de cinema",
    "Fotógrafo",
    "Escritor",
    "Jornalista",
    "Advogado",
    "Juiz",
    "Engenheiro",
    "Arquiteto",
    "Carpinteiro",
    "Bombeiro",
    "Enfermeira",
    "Piloto",
    "Caminhoneiro",
    "Garçom",
    "Barista",
    "Cabeleireiro",
    "Maquiador",
    "Costureira",
    "Estilista",
    "Dançarino",
    "Malabarista",
    "Acrobata",
    "Lutador de boxe",
    "Karateca",
    "Mímico",
    "Atleta olímpico",
    "Jogador",
    "Arqueiro",
    "Cavaleiro",
    "Corredor",
    "Maratonista",
    "Turista",
    "Explorador",
    "Cientista",
    "Programador",
    "Desenhista",
    "Filósofo",
    "Psicólogo",
    "Tradutor",
    "Bibliotecário",
    "Arqueólogo",
    "Meteorologista",
    "Astrônomo",
    "Geólogo",
    "Botânico",
    "Agricultor",
    "Padeiro",
    "Confeiteiro",
    "Açougueiro"
  ];
  static List<String> filmes = [
    "Titanic",
    "Avatar",
    "O Senhor dos Anéis",
    "Harry Potter",
    "Star Wars",
    "O Poderoso Chefão",
    "Pulp Fiction",
    "Forrest Gump",
    "Clube da Luta",
    "O Exterminador do Futuro",
    "Matrix",
    "Jurassic Park",
    "Indiana Jones",
    "De Volta para o Futuro",
    "O Rei Leão",
    "Homem-Aranha",
    "Batman",
    "Superman",
    "Vingadores",
    "Os Incríveis",
    "Shrek",
    "Toy Story",
    "Procurando Nemo",
    "A Bela e a Fera",
    "Aladdin",
    "Frozen",
    "Moana",
    "Mulan",
    "Cinderela",
    "Branca de Neve",
    "A Pequena Sereia",
    "Alice no País das Maravilhas",
    "Caça-Fantasmas",
    "Rocky",
    "Rambo",
    "Gladiador",
    "Coração Valente",
    "O Código Da Vinci",
    "Anjos e Demônios",
    "O Iluminado",
    "Psicose",
    "Laranja Mecânica",
    "2001: Uma Odisseia no Espaço",
    "Interestelar",
    "Blade Runner",
    "Clube da Luta",
    "O Resgate do Soldado Ryan",
    "O Pianista",
    "Cisne Negro",
    "Coringa",
    "Kill Bill",
  ];
  static List<String> animais = [
    "Cachorro",
    "Gato",
    "Leão",
    "Tigre",
    "Elefante",
    "Girafa",
    "Cavalo",
    "Vaca",
    "Porco",
    "Coelho",
    "Macaco",
    "Urso",
    "Rinoceronte",
    "Cobra",
    "Jacaré",
    "Tartaruga",
    "Pinguim",
    "Pato",
    "Galinha",
    "Galo",
    "Papagaio",
    "Pombo",
    "Coruja",
    "Peixe",
    "Baleia",
    "Golfinho",
    "Sapo",
    "Rato",
    "Morcego",
    "Canguru",
    "Gorila",
    "Lobo",
    "Esquilo",
    "Foca",
    "Onça",
    "Pantera",
    "Javali",
    "Camelo",
    "Burro",
    "Pavão",
    "Cisne",
    "Ganso",
    "Corvo",
    "Pica-pau",
    "Caranguejo",
    "Polvo",
    "Lula",
    "Estrela-do-mar",
    "Mariposa",
    "Borboleta",
    "Formiga",
    "Abelha"
  ];

  static List<String> objetos = [
    "Bola de futebol",
    "Telefone",
    "Câmera",
    "Micro-ondas",
    "Vaso de planta",
    "Caixa de correio",
    "Guarda-chuva",
    "Escova de cabelo",
    "Martelo",
    "Faca de cozinha",
    "Chave de fenda",
    "Máquina de lavar",
    "Bicicleta",
    "Violão",
    "Óculos de sol",
    "Relógio de pulso",
    "Laptop",
    "Televisão",
    "Abajur",
    "Saco de dormir",
    "Binóculos",
    "Microfone",
    "Cafeteira",
    "Carrinho de supermercado",
    "Patins",
    "Balão/Bexiga",
    "Cadeira de praia",
    "Ventilador",
    "Cinto",
    "Pendrive",
    "Vela",
    "Chapéu",
    "Colher de pau",
    "Pirulito",
    "Guitarra",
    "Salto alto",
    "Frigideira",
    "Livro",
    "Lâmpada",
    "Escada",
    "Binóculos",
    "Relógio de parede",
    "Caixa de joias",
    "Espelho",
    "Caneca",
    "Balança",
    "Estetoscópio",
    "Bomba de ar",
    "Pincel",
    "Rádio",
    "Raquete",
    "Máquina de costura",
    "Mala",
    "Microscópio",
    "Tabuleiro de xadrez",
    "Cesto de roupa",
    "Raquete",
    "Escova de dentes",
    "Almofada",
    "Skate",
    "Teclado",
    "Fone de ouvido",
    "Churrasqueira",
    "Capacete",
    "Caixa de ferramentas",
    "Máscara de mergulho",
    "Quadro",
    "Trompete",
    "Joia",
    "Dardo",
    "Escudo",
    "Violino",
    "Serra elétrica",
    "Bengala",
    "Prancha de surf",
    "Álbum de fotos",
    "Telescópio",
    "Piano",
    "Corda",
    "Martelo",
    "Pulseira",
    "Pão",
    "Barril",
    "Roda de carro",
    "Pente",
    "Escova de dentes",
    "Cadeado",
    "Engradado de cerveja",
    "Binóculos",
    "Mesa de pingue-pongue",
    "Bússola",
    "Máquina de escrever",
    "Taco de beisebol",
    "Cadeira de rodas",
    "Acordeão",
    "Gaita",
  ];
}
