class ListWords {
  static List<String> verbos = [
    "Correr",
    "Dançar",
    "Comer",
    "Beber",
    "Ler",
    "Escrever",
    "Nadar",
    "Cantar",
    "Dormir",
    "Aplaudir",
    "Cortar",
    "Cozinhar",
    "Pular",
    "Chorar",
    "Sorrir",
    "Brincar",
    "Telefonar",
    "Desenhar",
    "Bater",
    "Ajudar",
    "Abraçar",
    "Beijar",
    "Lavar",
    "Varrer",
    "Pintar",
    "Escovar",
    "Gritar",
    "Sussurrar",
    "Levantar",
    "Sentar",
    "Abrir",
    "Fechar",
    "Consertar",
    "Viajar",
    "Falar",
    "Escutar",
    "Olhar",
    "Esperar",
    "Caminhar",
    "Dirigir",
    "Comprar",
    "Vender",
    "Amarrar",
    "Desamarrar",
    "Construir",
    "Destruir",
    "Colher",
    "Plantar",
    "Pescar",
    "Cavar",
    "Subir",
    "Descer",
    "Procurar",
    "Encontrar",
    "Esconder",
    "Mostrar",
    "Deitar",
    "Tocar",
    "Fumar",
    "Morder",
    "Assoprar",
    "Treinar",
    "Jogar",
    "Lutar",
    "Cavalgar",
    "Navegar",
    "Patinar",
    "Esquiar",
    "Surfar"
  ];
  static List<String> geral = [
    "Natação",
    "Banho",
    "Musculação",
    "Flores",
    "Casa",
    "Igreja",
    "Chá",
    "Sol",
    "Árvore",
    "Música",
    "Pizza",
    "Sorvete",
    "Ônibus",
    "Maçã",
    "Estrela",
    "Basquete",
    "Triste",
    "Espirro",
    "Piada",
    "Chifres",
    "Balé",
    "Elevador",
    "Criança",
    "Bicicleta",
    "Tricô",
    "Crochê",
    "Costura",
    "Acampar",
    "Pular corda",
    "Soltar pipa",
    "Fazer careta",
    "Tirar foto",
    "Gravar vídeo",
    "Tocar violão",
    "Tocar piano",
    "Tocar bateria",
    "Tocar flauta",
    "Tocar saxofone",
    "Tocar violino",
    "Esquiar",
    "Correr maratona",
    "Levantar peso",
    "Fazer yoga",
    "Meditar",
    "Caminhada",
    "Escalada",
    "Rapel",
    "Voo livre",
    "Parapente",
    "Montar quebra-cabeça",
    "Futebol",
    "Frio",
    "Pirata",
    "Super-herói",
    "Princesa",
    "Samurai",
    "Ninja",
    "Vampiro",
    "Zumbi",
    "Estátua",
    "Pintor",
    "Bebê"
  ];
  static List<String> profissoes = [
    "Bailarina",
    "Doutor",
    "Astronauta",
    "Palhaço",
    "Soldado",
    "Detetive",
    "Chef de cozinha",
    "Policial",
    "Professor",
    "Dentista",
    "Mágico",
    "DJ",
    "Nadador",
    "Ciclista",
    "Surfista",
    "Esquiador",
    "Pescador",
    "Motorista",
    "Jardineiro",
    "Cantor",
    "Baterista",
    "Guitarrista",
    "Pianista",
    "Ator",
    "Diretor de cinema",
    "Fotógrafo",
    "Escritor",
    "Jornalista",
    "Advogado",
    "Juiz",
    "Engenheiro",
    "Arquiteto",
    "Carpinteiro",
    "Bombeiro",
    "Enfermeira",
    "Piloto",
    "Caminhoneiro",
    "Garçom",
    "Barista",
    "Cabeleireiro",
    "Maquiador",
    "Costureira",
    "Estilista",
    "Dançarino",
    "Malabarista",
    "Acrobata",
    "Lutador de boxe",
    "Karateca",
    "Mímico",
    "Atleta olímpico",
    "Jogador de basquete",
    "Jogador de tênis",
    "Jogador de vôlei",
    "Arqueiro",
    "Cavaleiro",
    "Corredor",
    "Maratonista",
    "Turista",
    "Explorador",
    "Cientista",
    "Químico",
    "Biólogo",
    "Físico",
    "Matemático",
    "Programador",
    "Designer",
    "Animador",
    "Cartunista",
    "Filósofo",
    "Historiador",
    "Psicólogo",
    "Sociólogo",
    "Antropólogo",
    "Linguista",
    "Tradutor",
    "Bibliotecário",
    "Arqueólogo",
    "Meteorologista",
    "Astrônomo",
    "Geólogo",
    "Oceanógrafo",
    "Ecologista",
    "Biólogo marinho",
    "Zoologista",
    "Botânico",
    "Agricultor",
    "Padeiro",
    "Confeiteiro",
    "Açougueiro"
  ];
  static List<String> filmes = [
    "Titanic",
    "Avatar",
    "O Senhor dos Anéis",
    "Harry Potter",
    "Star Wars",
    "O Poderoso Chefão",
    "Pulp Fiction",
    "Forrest Gump",
    "Clube da Luta",
    "O Exterminador do Futuro",
    "Matrix",
    "Jurassic Park",
    "Indiana Jones",
    "De Volta para o Futuro",
    "O Rei Leão",
    "Homem-Aranha",
    "Batman",
    "Superman",
    "Vingadores",
    "Os Incríveis",
    "Shrek",
    "Toy Story",
    "Procurando Nemo",
    "A Bela e a Fera",
    "Aladdin",
    "Frozen",
    "Moana",
    "Mulan",
    "Cinderela",
    "Branca de Neve",
    "A Pequena Sereia",
    "Alice no País das Maravilhas",
    "O Mágico de Oz",
    "E.T. o Extraterrestre",
    "Caça-Fantasmas",
    "Rocky",
    "Rambo",
    "Gladiador",
    "Coração Valente",
    "O Código Da Vinci",
    "Anjos e Demônios",
    "O Iluminado",
    "Psicose",
    "Laranja Mecânica",
    "2001: Uma Odisseia no Espaço",
    "Interestelar",
    "Inception",
    "Clube dos Cinco",
    "Curtindo a Vida Adoidado",
    "Os Caçadores da Arca Perdida",
    "Mad Max",
    "Blade Runner",
    "Alien",
    "O Sexto Sentido",
    "Clube da Luta",
    "Seven",
    "Os Suspeitos",
    "A Lista de Schindler",
    "O Resgate do Soldado Ryan",
    "O Pianista",
    "Cisne Negro",
    "A Origem",
    "Batman: O Cavaleiro das Trevas",
    "Coringa",
    "Kill Bill",
    "Django Livre"
  ];
  static List<String> animais = [
    "Cachorro",
    "Gato",
    "Leão",
    "Tigre",
    "Elefante",
    "Girafa",
    "Cavalo",
    "Vaca",
    "Porco",
    "Coelho",
    "Ovelha",
    "Macaco",
    "Urso",
    "Rinoceronte",
    "Hipopótamo",
    "Cobra",
    "Jacaré",
    "Tartaruga",
    "Pinguim",
    "Pato",
    "Galinha",
    "Galo",
    "Papagaio",
    "Pombo",
    "Águia",
    "Falcão",
    "Coruja",
    "Peixe",
    "Tubarão",
    "Baleia",
    "Golfinho",
    "Sapo",
    "Rato",
    "Morcego",
    "Canguru",
    "Panda",
    "Gorila",
    "Arara",
    "Lobo",
    "Coiote",
    "Gambá",
    "Porquinho-da-índia",
    "Hamster",
    "Esquilo",
    "Lontra",
    "Foca",
    "Morsa",
    "Leopardo",
    "Onça",
    "Pantera",
    "Javali",
    "Camelo",
    "Dromedário",
    "Burro",
    "Lhama",
    "Avestruz",
    "Flamingo",
    "Pavão",
    "Cisne",
    "Ganso",
    "Corvo",
    "Pica-pau",
    "Pelicano",
    "Garça",
    "Caranguejo",
    "Polvo",
    "Lula",
    "Estrela-do-mar",
    "Mariposa",
    "Borboleta",
    "Grilo",
    "Gafanhoto",
    "Formiga",
    "Abelha"
  ];

  static List<String> objetos = [
    "Bola de futebol",
    "Telefone",
    "Câmera fotográfica",
    "Micro-ondas",
    "Vaso de planta",
    "Caixa de correio",
    "Guarda-chuva",
    "Escova de cabelo",
    "Martelo",
    "Faca de cozinha",
    "Chave de fenda",
    "Máquina de lavar roupa",
    "Bicicleta",
    "Violão",
    "Óculos de sol",
    "Relógio de pulso",
    "Laptop",
    "Televisão",
    "Abajur",
    "Saco de dormir",
    "Binóculos",
    "Microfone",
    "Cafeteira",
    "Carrinho de supermercado",
    "Patins",
    "Balão de festa",
    "Cadeira de praia",
    "Ventilador",
    "Cinto",
    "Pendrive",
    "Vela",
    "Chapéu",
    "Colher de pau",
    "Pirulito",
    "Guitarra",
    "Sapato de salto alto",
    "Barraca de acampamento",
    "Frigideira",
    "Livro",
    "Lâmpada",
    "Escada",
    "Binóculos",
    "Relógio de parede",
    "Caixa de joias",
    "Espelho",
    "Caneca",
    "Balança",
    "Estetoscópio",
    "Bomba de ar",
    "Pincel",
    "Bola de basquete",
    "Rádio",
    "Raquete de tênis",
    "Máquina de costura",
    "Mala de viagem",
    "Microscópio",
    "Tabuleiro de xadrez",
    "Cesto de roupa suja",
    "Raquete de pingue-pongue",
    "Escova de dentes",
    "Almofada",
    "Câmera de vídeo",
    "Skate",
    "Teclado de computador",
    "Ferramenta de jardim",
    "Fone de ouvido",
    "Relógio de areia",
    "Churrasqueira",
    "Capacete de ciclismo",
    "Caixa de ferramentas",
    "Máscara de mergulho",
    "Quadro branco",
    "Trompete",
    "Joia",
    "Patins em linha",
    "Caixa de lenços",
    "Dardo",
    "Escudo",
    "Violino",
    "Serra elétrica",
    "Bengala",
    "Prancha de surf",
    "Álbum de fotos",
    "Telescópio",
    "Cesta de piquenique",
    "Skateboard",
    "Bomba d'água",
    "Piano",
    "Corda de pular",
    "Martelo de juiz",
    "Pulseira",
    "Pão",
    "Barril",
    "Roda de carro",
    "Pente",
    "Capacete de segurança",
    "Escova de pintura",
    "Árvore de Natal",
    "Cadeado",
    "Engradado de cerveja",
    "Microfone de karaokê",
    "Carretel de linha",
    "Binóculos de visão noturna",
    "Mesa de pingue-pongue",
    "Bússola",
    "Máquina de escrever",
    "Taco de beisebol",
    "Cadeira de rodas",
    "Acordeão",
    "Gaita",
    "Escudo de futebol americano"
  ];
}
