class ListWords {
  static List<String> verbos = [
    'Abraçar',
    'Abrir',
    'Acenar',
    'Adorar',
    'Agachar',
    'Agarrar',
    'Ajoelhar',
    'Ajudar',
    'Alongar',
    'Amar',
    'Amarrar',
    'Apagar',
    'Apertar',
    'Aplaudir',
    'Aprender',
    'Arremessar',
    'Arrotar',
    'Assoprar',
    'Assustar',
    'Atender',
    'Atirar',
    'Avisar',
    'Babar',
    'Balançar',
    'Bater',
    'Beber',
    'Beijar',
    'Berrar',
    'Bocejar',
    'Bolar',
    'Bordar',
    'Brigar',
    'Brincar',
    'Cambalear',
    'Caminhar',
    'Cantar',
    'Carregar',
    'Cavalgar',
    'Cavar',
    'Chicotear',
    'Chorar',
    'Chutar',
    'Cicatrizar',
    'Clarificar',
    'Cochilar',
    'Colar',
    'Colher',
    'Comer',
    'Comparar',
    'Comprar',
    'Comprimir',
    'Confundir',
    'Congelar',
    'Consertar',
    'Construir',
    'Correr',
    'Cortar',
    'Cozinhar',
    'Criticar',
    'Cuspir',
    'Dançar',
    'Debater',
    'Declarar',
    'Defender',
    'Degustar',
    'Deitar',
    'Demorar',
    'Derrapar',
    'Desabar',
    'Desamarrar',
    'Descansar',
    'Descer',
    'Descongelar',
    'Descrever',
    'Desdobrar',
    'Desenhar',
    'Desenrolar',
    'Desenroscar',
    'Desligar',
    'Desmaiar',
    'Destruir',
    'Dirigir',
    'Dobrar',
    'Dominar',
    'Dormir',
    'Embalar',
    'Embrulhar',
    'Empurrar',
    'Encaixar',
    'Encontrar',
    'Encostar',
    'Enfeitar',
    'Engatinhar',
    'Enrolar',
    'Enroscar',
    'Ensinar',
    'Enterrar',
    'Envolver',
    'Erguer',
    'Escalar',
    'Esclarecer',
    'Esconder',
    'Escovar',
    'Escrever',
    'Escutar',
    'Esfriar',
    'Esmagar',
    'Espalhar',
    'Esperar',
    'Espirrar',
    'Espremer',
    'Esquiar',
    'Esquivar',
    'Estacionar',
    'Esticar',
    'Estremecer',
    'Falar',
    'Farejar',
    'Fechar',
    'Ficar',
    'Fingir',
    'Flutuar',
    'Folhear',
    'Fotografar',
    'Franzir',
    'Fumar',
    'Furar',
    'Gargalhar',
    'Gesticular',
    'Gritar',
    'Ilustrar',
    'Imaginar',
    'Imitar',
    'Inalar',
    'Inclinar',
    'Iniciar',
    'Injetar',
    'Inventar',
    'Jogar',
    'Lavar',
    'Ler',
    'Levantar',
    'Ligar',
    'Limpar',
    'Lutar',
    'Machucar',
    'Mastigar',
    'Mergulhar',
    'Misturar',
    'Morder',
    'Mostrar',
    'Nadar',
    'Navegar',
    'Observar',
    'Olhar',
    'Organizar',
    'Palpitar',
    'Participar',
    'Passar',
    'Patinar',
    'Pedir',
    'Pegar',
    'Pendurar',
    'Perdoar',
    'Perecer',
    'Perseguir',
    'Pescar',
    'Pintar',
    'Piscar',
    'Plantar',
    'Preencher',
    'Preparar',
    'Preservar',
    'Procurar',
    'Prometer',
    'Proteger',
    'Pular',
    'Quebrar',
    'Rastejar',
    'Realizar',
    'Rebolar',
    'Recuperar',
    'Reduzir',
    'Refletir',
    'Regar',
    'Remover',
    'Reparar',
    'Resgatar',
    'Respirar',
    'Revelar',
    'Rodar',
    'Rodopiar',
    'Saltar',
    'Salvar',
    'Sangrar',
    'Seguir',
    'Sentar',
    'Separar',
    'Silenciar',
    'Sobreviver',
    'Sorrir',
    'Subir',
    'Sugerir',
    'Surfar',
    'Surpreender',
    'Sussurrar',
    'Tapear',
    'Telefonar',
    'Tentar',
    'Tocar',
    'Tombar',
    'Trabalhar',
    'Treinar',
    'Tropeçar',
    'Ultrapassar',
    'Unir',
    'Vaguear',
    'Varrer',
    'Vencer',
    'Vender',
    'Viajar',
    'Vibrar',
    'Visitar',
    'Voltar',
    'Zombar'
  ];

  static List<String> geral = [
    "Amor",
    "Amizade",
    "Natureza",
    "Cidade",
    "Família",
    "Educação",
    "Tecnologia",
    "Cultura",
    "Saúde",
    "Esporte",
    "Viagem",
    "Trabalho",
    "Música",
    "Arte",
    "Literatura",
    "Ciências",
    "Filme",
    "Teatro",
    "Política",
    "Filosofia",
    "Religião",
    "Linguagem",
    "Psicologia",
    "Antropologia",
    "Matemática",
    "Física",
    "Economia",
    "Direito",
    "Esquerdo",
    "Destro",
    "Canhoto",
    "Farmácia",
    "Nutrição",
    "Genética",
    "Botânica",
    "Astronomia",
    "Astrologia",
    "Meteorologia",
    "Futebol",
    "Basquete",
    "Voleibol",
    "Tênis",
    "Natação",
    "Xadrez",
    "Dominó",
    "Pipa",
    "Boneca",
    "Carrinho",
    "Fantasia",
    "Super-Herói",
    "Princesa",
    "Pirata",
    "Monstro",
    "Pulo",
    "Sorriso",
    "Abraço",
    "Choro",
    "Felicidade",
    "Tristeza",
    "Beleza",
    "Coragem",
    "Inteligência",
    "Força",
    "Rapidez",
    "Calma",
    "Alegria",
    "Medo",
    "Surpresa",
    "Noite",
    "Dia",
    "Estação",
    "Clima",
    "Tempo",
    "Passado",
    "Presente",
    "Futuro",
    "Memória",
    "Sonho",
    "Labirinto",
    "Mistério",
    "Camuflagem",
    "Invisível",
    "Faraó",
    "Arqueologia",
    "Magia",
    "Exploração",
    "Violinista",
    "Marionete",
    "Ilusão",
    "Contorcionismo",
    "Carrossel",
    "Coral",
    "Maratona",
    "Escalada",
    "Ginástica",
    "Patins",
    "Aviador",
    "Cachoeira",
    "Relâmpago",
    "Vulcão",
    "Aurora",
    "Nômade",
    "Casa",
    "Apartamento",
    "Escola",
    "Hospital",
    "Escritório",
    "Loja",
    "Restaurante",
    "Cinema",
    "Parque",
    "Museu",
    "Templo",
    "Mesquita",
    "Praia",
    "Montanha",
    "Floresta",
    "Deserto",
    "Espaço",
    "Banho",
    "Musculação",
    "Flores",
    "Chá",
    "Sol",
    "Árvore",
    "Pizza",
    "Sorvete",
    "Ônibus",
    "Maçã",
    "Estrela",
    "Triste",
    "Espirro",
    "Piada",
    "Chifres",
    "Balé",
    "Elevador",
    "Criança",
    "Bicicleta",
    "Tricô",
    "Crochê",
    "Costura",
    "Acampar",
    "Esquiar",
    "Meditar",
    "Caminhada",
    "Rapel",
    "Voo",
    "Parapente",
    "Quebra-Cabeça",
    "Frio",
    "Samurai",
    "Ninja",
    "Vampiro",
    "Zumbi",
    "Estátua",
    "Pintor",
    "Bebê",
    "Luz",
    "Sombra",
    "Shopping",
    "Pesadelo",
    "Fome",
    "Sede",
    "Preguiça",
    "Excitação",
    "Alívio",
    "Corrida",
    "Espreguiçar",
    "Aplauso",
    "Mistério",
    "Férias",
    "Trabalho em Equipe",
    "Acidente",
    "Promessa",
    "Debate",
    "Experimento",
    "Redemoinho",
    "Raio de Sol",
    "Nevoeiro",
    "Tsunami"
  ];

  static List<String> profissoes = [
    "Bailarina",
    "Doutor",
    "Astronauta",
    "Palhaço",
    "Soldado",
    "Detetive",
    "Chef de cozinha",
    "Policial",
    "Professor",
    "Dentista",
    "Mágico",
    "DJ",
    "Nadador",
    "Ciclista",
    "Surfista",
    "Esquiador",
    "Pescador",
    "Motorista",
    "Jardineiro",
    "Cantor",
    "Baterista",
    "Guitarrista",
    "Pianista",
    "Ator",
    "Diretor de cinema",
    "Fotógrafo",
    "Escritor",
    "Jornalista",
    "Advogado",
    "Juiz",
    "Engenheiro",
    "Arquiteto",
    "Carpinteiro",
    "Bombeiro",
    "Enfermeira",
    "Piloto",
    "Caminhoneiro",
    "Garçom",
    "Barista",
    "Cabeleireiro",
    "Maquiador",
    "Costureira",
    "Estilista",
    "Dançarino",
    "Malabarista",
    "Acrobata",
    "Lutador de boxe",
    "Mímico",
    "Atleta olímpico",
    "Jogador",
    "Arqueiro",
    "Cavaleiro",
    "Corredor",
    "Maratonista",
    "Turista",
    "Cientista",
    "Programador",
    "Desenhista",
    "Filósofo",
    "Psicólogo",
    "Tradutor",
    "Bibliotecário",
    "Arqueólogo",
    "Meteorologista",
    "Astrônomo",
    "Botânico",
    "Agricultor",
    "Padeiro",
    "Confeiteiro",
    "Açougueiro"
  ];
  static List<String> filmes = [
    "Titanic",
    "Avatar",
    "O Senhor dos Anéis",
    "Harry Potter",
    "Star Wars",
    "O Poderoso Chefão",
    "Pulp Fiction",
    "Forrest Gump",
    "Clube da Luta",
    "O Exterminador do Futuro",
    "Matrix",
    "Jurassic Park",
    "Indiana Jones",
    "De Volta para o Futuro",
    "O Rei Leão",
    "Homem-Aranha",
    "Batman",
    "Superman",
    "Vingadores",
    "Os Incríveis",
    "Shrek",
    "Toy Story",
    "Procurando Nemo",
    "A Bela e a Fera",
    "Aladdin",
    "Frozen",
    "Moana",
    "Mulan",
    "Cinderela",
    "Branca de Neve",
    "A Pequena Sereia",
    "Alice no País das Maravilhas",
    "Caça-Fantasmas",
    "Rocky",
    "Rambo",
    "Gladiador",
    "Coração Valente",
    "O Código Da Vinci",
    "Anjos e Demônios",
    "O Iluminado",
    "Psicose",
    "Laranja Mecânica",
    "2001: Uma Odisseia no Espaço",
    "Interestelar",
    "Blade Runner",
    "Clube da Luta",
    "O Resgate do Soldado Ryan",
    "O Pianista",
    "Cisne Negro",
    "Coringa",
    "Kill Bill",
  ];
  static List<String> animais = [
    "Cachorro",
    "Gato",
    "Leão",
    "Tigre",
    "Elefante",
    "Girafa",
    "Cavalo",
    "Vaca",
    "Porco",
    "Coelho",
    "Macaco",
    "Urso",
    "Rinoceronte",
    "Cobra",
    "Jacaré",
    "Tartaruga",
    "Pinguim",
    "Pato",
    "Galinha",
    "Galo",
    "Papagaio",
    "Pombo",
    "Coruja",
    "Peixe",
    "Baleia",
    "Golfinho",
    "Sapo",
    "Rato",
    "Morcego",
    "Canguru",
    "Gorila",
    "Lobo",
    "Esquilo",
    "Foca",
    "Onça",
    "Pantera",
    "Javali",
    "Camelo",
    "Burro",
    "Pavão",
    "Cisne",
    "Ganso",
    "Corvo",
    "Pica-pau",
    "Caranguejo",
    "Polvo",
    "Lula",
    "Mariposa",
    "Borboleta",
    "Formiga",
    "Abelha"
  ];

  static List<String> objetos = [
    'Abajur',
    'Acordeão',
    'Alicate',
    'Almofada',
    'Arco',
    'Aspirador de pó',
    'Balança',
    'Balão/Bexiga',
    'Baralho',
    'Barril',
    'Bengala',
    'Bicicleta',
    'Binóculos',
    'Bola de futebol',
    'Bomba de ar',
    'Borracha',
    'Brinquedo',
    'Bumerangue',
    'Bússola',
    'Cabide',
    'Cachimbo',
    'Cadeado',
    'Cadeira de praia',
    'Cadeira de rodas',
    'Caderno',
    'Cafeteira',
    'Caixa',
    'Caixa de correio',
    'Caixa de ferramentas',
    'Caixa de joias',
    'Caneca',
    'Capacete',
    'Carregador de celular',
    'Carrinho de supermercado',
    'Cavalete',
    'Cesta',
    'Cesto de roupa',
    'Chaleira',
    'Chapéu',
    'Chave',
    'Chave de fenda',
    'Chave inglesa',
    'Chicote',
    'Churrasqueira',
    'Cinto',
    'Cofre',
    'Colar',
    'Colher de pau',
    'Controle de videogame',
    'Controle remoto',
    'Copo',
    'Corda',
    'Cortador de grama',
    'Cortador de pizza',
    'Cortina',
    'Câmera',
    'Câmera de segurança',
    'Dardo',
    'Engradado de cerveja',
    'Envelope',
    'Escada',
    'Escova de cabelo',
    'Escova de dentes',
    'Escudo',
    'Espada',
    'Espelho',
    'Estetoscópio',
    'Estilete',
    'Estátua',
    'Faca',
    'Faca de cozinha',
    'Fone de ouvido',
    'Frigideira',
    'Gaita',
    'Grampeador',
    'Guarda-chuva',
    'Guitarra',
    'Jaqueta',
    'Joia',
    'Lancha',
    'Lanterna',
    'Notebook',
    'Livro',
    'Lixeira',
    'Luminária',
    'Luva',
    'Lâmpada',
    'Mala',
    'Maleta',
    'Martelo',
    'Mesa de pingue-pongue',
    'Micro-ondas',
    'Microfone',
    'Microscópio',
    'Mochila',
    'Moeda',
    'Monitor',
    'Máquina de costura',
    'Máquina de escrever',
    'Máquina de lavar',
    'Máscara de mergulho',
    'Pandeiro',
    'Patinete',
    'Patins',
    'Pendrive',
    'Pente',
    'Piano',
    'Pincel',
    'Pirulito',
    'Placa de sinalização',
    'Ponteiro laser',
    'Porta-copos',
    'Prancha de surf',
    'Prateleira',
    'Pulseira',
    'Pão',
    'Quadro',
    'Quadro branco',
    'Quebra-cabeça',
    'Quimono',
    'Raquete',
    'Rede de pesca',
    'Refrigerador',
    'Relógio de bolso',
    'Relógio de parede',
    'Relógio de pulso',
    'Roda de carro',
    'Rolo de pintura',
    'Roteador',
    'Rádio',
    'Régua',
    'Sabonete',
    'Saco de dormir',
    'Salto alto',
    'Sandália',
    'Serra elétrica',
    'Sino',
    'Skate',
    'Tablet',
    'Tabuleiro de xadrez',
    'Taco de beisebol',
    'Tapete',
    'Teclado',
    'Telefone',
    'Telescópio',
    'Televisão',
    'Tenda',
    'Tesoura',
    'Toca-discos',
    'Torneira',
    'Travesseiro',
    'Trompete',
    'Tubo de ensaio',
    'Tábua de passar roupa',
    'Vaso de planta',
    'Vassoura',
    'Vela',
    'Ventilador',
    'Violino',
    'Violão',
    'Xícara',
    'Ábaco',
    'Álbum de fotos',
    'Óculos de sol'
  ];
}
